[tool.poetry]
name = "isamples_metadata"
version = "0.3"
description = ""
authors = ["Danny Mandel <danny.mandel@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8.3"
pytest = "^6.2.3"
requests = "^2.25.1"
fasttext = "^0.9.2"
pydantic = "^1.8.2"
python-dotenv = "^0.19.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
