project:
  type: website
  output-dir: ../../docs

format:
  html:
    theme:
      - cosmo
      - styles.scss

website:
  title: "iSamples Model"
  page-footer:
    left: >
        © Copyright 2020, iSamples Project.

        This material is based upon work supported by the National Science Foundation under Grant Numbers
        [2004839](https://nsf.gov/awardsearch/showAward?AWD_ID=2004839),
        [2004562](https://nsf.gov/awardsearch/showAward?AWD_ID=2004562),
        [2004642](https://nsf.gov/awardsearch/showAward?AWD_ID=2004642),
        and [2004815](https://nsf.gov/awardsearch/showAward?AWD_ID=2004815).
        Any opinions, findings, and conclusions or recommendations expressed in this material are those of the author(s) and do not necessarily reflect the views of the [National Science Foundation](https://nsf.gov/).
  repo-url: https://github.com/isamplesorg/metadata
  repo-actions: [edit, issue]
  sidebar:
    style: "docked"
    search: true
    tools:
      - icon: table
        href: https://hyde.cyverse.org/isamples_central/ui/
      - icon: github
        href: https://github.com/isamplesorg
      - icon: slack
        href: https://isamples.slack.com/
      - icon: twitter
        href: https://twitter.com/isamplesorg

metadata-files:
  - _model.yml
