name: Build and publish documentation

# Docs are built with a push to main or when triggered manually.
# Docs are placed in the gh-pages branch. 
#
# Note that manually triggering this action from another branch 
# will replace the gh-pages branch
on:
  push:
    branches:
      - main
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: sudo pip install -r requirements.txt

      - name: Parse vocabularies
        uses: isamplesorg/vocabularies@main
        with:
          action: docs
          path: ${{ github.workspace }}/build/docs/vocabularies

      - name: List the output of the vocabulary
        run: ls -l ${{ github.workspace }}/build/docs/vocabularies
        
      - name: List the output of the docs directory
        run: ls -l ${{ github.workspace }}/build/docs/
        
      # - name: Gen docs without makefile
      #   run: sudo python tools/docgen.py --log_level WARNING --dialect quarto --sort-by name --format quarto --mergeimports --metadata --directory build/docs src/schemas/isamples_core.yaml

      - name: Render documentation
        run: make gen-docs

      - name: Publish documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
